apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: local/app:pitermar
        ports:
        - containerPort: 8000
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        readinessProbe:
          httpGet:
            path: /id
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /hostname
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-namespace
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - name: http
    port: 8000
    targetPort: 8000